### PR TITLE
Test: increase dynamodb timeout

### PR DESCRIPTION
**Pull request by t1707**
Fix CI test

### CODE REVIEW

**Comment by t1707** [comment]
@paualarco Hi, I tried increasing the timeout and want to rebuild the CI. Can you provide me the access or is ti too early more me to get the access?

**Comment by paualarco** [comment]
> @paualarco Hi, I tried increasing the timeout and want to rebuild the CI. Can you provide me the access or is it too early for me to get the access?

@t1707 I am not in charge of access management, but I guess you can do that in your fork `t1707/monix-connect` or also just by pushing the same commit :)

**Comment by Avasil** [comment]
I've granted write permissions to the repo, should be more convenient

**Comment by t1707** [comment]
I increased the timeout but still showing the timeout error, so I guess we need to look from any other corner.

**Comment by paualarco** [comment]
> I increased the timeout but still showing the timeout error, so I guess we need to look from any other corner.

found out the error this morning, it is not solved from code but from the docker compose file. We were using latest version which its an error.

**Comment by t1707** [comment]
> found out the error this morning, it is not solved from code but from the docker compose file. We were using latest version which its an error.

I see, so I'll just close this one

**Pull request closed without merging**
